# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='brabch',
            new_name='brach_number',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='title',
        ),
        migrations.AddField(
            model_name='stores',
            name='branch_email_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stores',
            name='name_of_store',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
