# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190116_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='image',
            field=models.ImageField(default='pic.jpg', upload_to='stores/'),
        ),
    ]
