# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190115_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='neighborhood',
        ),
        migrations.DeleteModel(
            name='NeighborHood',
        ),
    ]
