# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20190116_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='brach_number',
        ),
    ]
