# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_schools_brach_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='stores',
        ),
    ]
