# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_rating_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='features',
            field=models.TextField(default='cool', max_length=300),
        ),
    ]
