# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_stores_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='features',
            field=models.CharField(default='cool', max_length=300),
        ),
    ]
