# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20190117_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='features',
        ),
    ]
